###
# create database loja_de_carros_development ;
# create database loja_de_carros_test ;
# create database loja_de_carros_production ;
#
# grant all on loja_de_carros_development.* to loja@'localhost' identified by 'loja';
# grant all on loja_de_carros_test.*        to loja@'localhost' identified by 'loja';
# grant all on loja_de_carros_production.*  to loja@'localhost' identified by 'loja';
# grant all on loja_de_carros_development.* to loja@'localhost' identified by 'loja';
# grant all on loja_de_carros_test.*        to loja@'localhost' identified by 'loja';
# grant all on loja_de_carros_production.*  to loja@'localhost' identified by 'loja';
# flush privileges;
###

development:
  adapter: mysql2
  host: localhost
  database: loja_de_carros_development
  username: loja
  password: loja
  pool: 5
  encoding: utf8
  reconnect: false


test:
  adapter: mysql2
  host: localhost
  database: loja_de_carros_test
  username: loja
  password: loja
  pool: 5
  encoding: utf8
  reconnect: false


production:
  adapter: mysql2
  host: localhost
  database: loja_de_carros_production
  username: loja
  password: loja
  pool: 5
  encoding: utf8
  reconnect: false


